const STATUS_CODE = {
  CREATED: '201',
  SUCCESS: '200',
  BAD_REQUEST: '400',
  UNAUTHORIZED: '401',
  FORBIDDEN: '403',
  RESOURCE_NOT_FOUND: '404',
  DUPLICATE_RESOURCE: '409',
  INTERNAL_SERVER_ERROR: '500',
};

module.exports = STATUS_CODE;